#Week 02 assignment on programming activty (prove)
#TASK: Create a "MADLIB" type of program.
#PURPOSE: Use a systematic approach to writting code

print('Please enter the following information:')
print()
adjective_one = input('Adjective:')
animal = input('Animal:')
verb_one = input('Verb:')
exclamation = input('exclamation:')
verb_two = input('Verb:')
verb_three = input('Verb:')
pronoun = input('Pronoun:')
adjective_two = input('Adjective:')
verb_four = input('Verb:')
verb_five = input('Verb:')

print()
print('----------------------------')
print()
print('\nYour story is')
print()
print('The other day, I was really in trouble. It all started when I saw a very')
print(f'{adjective_one} {animal} {verb_one} down the hallway. "{exclamation.capitalize()}!" I yelled. But all')
print(f'I could think to do was to {verb_two} over and over. Miracolously,')
print(f'that caused it to stop, but not before it tried to {verb_three}')
print(f'right in front of my family. {pronoun.capitalize()} was such an {adjective_two} experience,')
print(f'I {verb_four} over and over again each time I {verb_five} it.')
print()
print('---------------------------------------------------------------------------------------------------')
end = input('.')