# Week 03 assignment on programming
# Author: Emediong Edet
print('Part one:')
print()
print('Prompt for the neccessary Info. then compute and display the areas.')
print()
print()
print()
print('---------------------------------')
square_length = float(input('What is the length of a side of the square:'))
area_1 = square_length ** 2
print(f'The area of the side of the square is: {area_1} ')
print()
print()
print()
print('-----------------------------------------------')
rectangle_length = float(input('What is the length of rectangle:'))
rectangle_width = float(input('What is the width of the rectangle:'))
area_2 = rectangle_length * rectangle_width
print(f'The area of the rectangle is: {area_2} ')
print()
print()
print()
print('----------------------------------------------------------------')
circle_radius = float(input('What is the radius of the circle:'))
area_3 = 3.1416 * (circle_radius ** 2)
print(f'The area of the circle is: {area_3}')
print('Part 2:')
print()
print()
print()
print('"Strecth 1"')
print('--------------------------------------------------------------------------')
print('Use the built in value of pi included in python "math" module')
print()
print()
print()
import math
circle_radius_2 = float(input('What is the radius of the circle:'))
area_4 = math.pi * (circle_radius_2 ** 2)
print(f'The area of the circle is: {area_4} ')
print()
print()
print()
print('"Strecth 2"')
print('-------------------------------------------------------------------------------------')
value = float(input('What is the general value to be used for the whole area caculation:'))
print()
square_area = value ** 2
circle_radius_3 = math.pi * (value ** 2)
cube_volume = value ** 3
sphere_radius = ( 4 / 3 ) * math.pi * ( value ** 3 )
print()
print()
print()
print(f'Area of a square is: {square_area}')
print(f'Area of a circle is: {circle_radius_3}')
print(f'Area of a volume is: {cube_volume}')
print(f'Area of a sphere is: {sphere_radius}')
End = input('...')
